### ISSUE TITLE
folder creation is not idempotent

### ISSUE THREAD

**Issue by ingvarrwvw** [codeaffen/phpipam-ansible-modules#100]
**Describe the bug**
When using option "is_folder" for creating folder, restart this play create the same folder in the same section

**To Reproduce**
create play:

- name: Create folder
  subnet:
    bla-bla-bla:
    **is_folder: true**

**Expected behavior**
Folder is created, but next run play will create new the same folder

**Versions:**

- Ansible: 2.13
- phpipam-ansible-modules: 1.6.1
- phpypam: 1.0.2

**Comment by cmeissner** [comment]
Thank you @ingvarrwvw for bringing this to our attention. May I ask you to provide a ready to use playbook to reproduce the issue. We also are keen to know how you create Folder via GUI, can you please provide a click path idially with screenshots. 
Last if would be good to know which version of phpIPAM do you use.

**Comment by ingvarrwvw** [comment]
> Thank you @ingvarrwvw for bringing this to our attention. May I ask you to provide a ready to use playbook to reproduce the issue. We also are keen to know how you create Folder via GUI, can you please provide a click path idially with screenshots. Last if would be good to know which version of phpIPAM do you use.

Of course

Playbook:

- name: Ensure state of subnets
  subnet:
    app_id: "{{ app_id }}"
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    subnet: ""
    mask: ""
    description: "FOLDER_NAME"
    is_folder: true
    section: "SECTION_NAME"
    state: present
  collections:
    - codeaffen.phpipam

PHPIPAM version 1.4

Screenshot for creating folder via GUI:
![image](https://github.com/codeaffen/phpipam-ansible-modules/assets/45449926/866f30fd-ae0a-4de1-ad64-e5a9c19015a4)

**Comment by cmeissner** [comment]
Thank you for posting the information. I digged also a bit deeper and it seem that we need another controller for folders. 

Although the `folders` controller is an alias of `subnets` controller both behave different. 

***lookup folder via subnets controller***

```shell
$ curl -sk -XGET -H "phpipam-token: ${IPAM_TOKEN}" https://localhost:8443/api/ansible/subnets/10 | jq
{
  "code": 404,
  "success": false,
  "message": "No subnets found",
  "time": 0.006
}
```

***lookup folder via folders controller***

```shell
$ curl -sk -XGET -H "phpipam-token: ${IPAM_TOKEN}" https://localhost:8443/api/ansible/folders/10 | jq
{
  "code": 200,
  "success": true,
  "data": {
    "id": "10",
    "subnet": null,
    "mask": null,
    "sectionId": "1",
    "description": "172.16.0.0/20",
    "linked_subnet": null,
    "firewallAddressObject": null,
    "vrfId": null,
    "masterSubnetId": "0",
    "allowRequests": "0",
    "vlanId": null,
    "showName": "0",
    "device": "0",
    "permissions": "{\"3\":\"1\",\"2\":\"2\"}",
    "pingSubnet": "0",
    "discoverSubnet": "0",
    "resolveDNS": "0",
    "DNSrecursive": "0",
    "DNSrecords": "0",
    "nameserverId": "0",
    "scanAgent": null,
    "customer_id": null,
    "isFolder": "1",
    "isFull": "0",
    "isPool": "0",
    "tag": "2",
    "threshold": "0",
    "location": null,
    "editDate": null,
    "lastScan": null,
    "lastDiscovery": null
  },
  "time": 0.008
}
```

This seem to be the root cause of the observed behavior. To guarantee idempotence we neet to query for existing entities before creating one. As the `subnets` controller don't return an entity the module assumes that there exists no one and create it again.

I can promise a quick bugfix but I'll do my best.

**Comment by cmeissner** [comment]
@ingvarrwvw I'm happy to announce that I found some time to implement the mentioned `folder` module (see #103). May I ask you to test if it meet your needs?

The module can manage folders and nested folders (via `parent` parameter). We did not implement association of subnets to folders yet but we will work on that feature asap.

Beware of an issue in phpIPAM webUI, here you can create a folder with a given name multiple times. The new module will always manages the entity with the smallest id. We always recommend to manage phpIPAM entities only through ansible if we provide a module for them.

**Comment by ingvarrwvw** [comment]
great news.
I tried to create a folder and got an error:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: phpypam.core.exceptions.PHPyPAMInvalidSyntax: Invalid filter_by
failed: [localhost] (item={'key': 'backbone', 'value': {'subnet': '', 'mask': ''}}) => {"ansible_loop_var": "subnet_item", "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1693213365.2240975-523951-208854634902741/AnsiballZ_folder.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1693213365.2240975-523951-208854634902741/AnsiballZ_folder.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1693213365.2240975-523951-208854634902741/AnsiballZ_folder.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.codeaffen.phpipam.plugins.modules.folder', init_globals=dict(_module_fqn='ansible_collections.codeaffen.phpipam.plugins.modules.folder', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_folder_payload_leqc2rjz/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/modules/folder.py\", line 109, in <module>\n  File \"/tmp/ansible_folder_payload_leqc2rjz/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/modules/folder.py\", line 105, in main\n  File \"/tmp/ansible_folder_payload_leqc2rjz/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/module_utils/phpipam_helper.py\", line 602, in run\n  File \"/tmp/ansible_folder_payload_leqc2rjz/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/module_utils/phpipam_helper.py\", line 572, in ensure_entity\n  File \"/tmp/ansible_folder_payload_leqc2rjz/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/module_utils/phpipam_helper.py\", line 268, in find_current_entity\n  File \"/tmp/ansible_folder_payload_leqc2rjz/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/module_utils/phpipam_helper.py\", line 230, in find_folder\n  File \"/tmp/ansible_folder_payload_leqc2rjz/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/module_utils/phpipam_helper.py\", line 122, in find_entity\n  File \"/home/user/ansible/lib/python3.8/site-packages/phpypam/core/api.py\", line 167, in get_entity\n    return self._query(token=self._api_token, method=GET, path=_path, params=_params)\n  File \"/home/user/ansible/lib/python3.8/site-packages/phpypam/core/api.py\", line 124, in _query\n    raise PHPyPAMException(code=result['code'], message=result['message'])\n  File \"/home/user/ansible/lib/python3.8/site-packages/phpypam/core/exceptions.py\", line 44, in __init__\n    raise PHPyPAMInvalidSyntax(message=self._message)\nphpypam.core.exceptions.PHPyPAMInvalidSyntax: Invalid filter_by\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "subnet_item": {"key": "backbone", "value": {"mask": "", "subnet": ""}}}

**Comment by ingvarrwvw** [comment]
> @ingvarrwvw I'm happy to announce that I found some time to implement the mentioned `folder` module (see #103). May I ask you to test if it meet your needs?
> 
> The module can manage folders and nested folders (via `parent` parameter). We did not implement association of subnets to folders yet but we will work on that feature asap.
> 
> Beware of an issue in phpIPAM webUI, here you can create a folder with a given name multiple times. The new module will always manages the entity with the smallest id. We always recommend to manage phpIPAM entities only through ansible if we provide a module for them.

Great news!

With play:

- name: Create a folder in DC
  folder:
    app_id: "{{ app_id }}"
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    name: "BACKBONE"
    section: "section_name"
    state: present


i got error:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: phpypam.core.exceptions.PHPyPAMInvalidSyntax: Invalid filter_by
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1693214693.0495925-592783-163058673152802/AnsiballZ_folder.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1693214693.0495925-592783-163058673152802/AnsiballZ_folder.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1693214693.0495925-592783-163058673152802/AnsiballZ_folder.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.codeaffen.phpipam.plugins.modules.folder', init_globals=dict(_module_fqn='ansible_collections.codeaffen.phpipam.plugins.modules.folder', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_folder_payload_pwk_rhr6/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/modules/folder.py\", line 109, in <module>\n  File \"/tmp/ansible_folder_payload_pwk_rhr6/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/modules/folder.py\", line 105, in main\n  File \"/tmp/ansible_folder_payload_pwk_rhr6/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/module_utils/phpipam_helper.py\", line 602, in run\n  File \"/tmp/ansible_folder_payload_pwk_rhr6/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/module_utils/phpipam_helper.py\", line 572, in ensure_entity\n  File \"/tmp/ansible_folder_payload_pwk_rhr6/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/module_utils/phpipam_helper.py\", line 268, in find_current_entity\n  File \"/tmp/ansible_folder_payload_pwk_rhr6/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/module_utils/phpipam_helper.py\", line 230, in find_folder\n  File \"/tmp/ansible_folder_payload_pwk_rhr6/ansible_folder_payload.zip/ansible_collections/codeaffen/phpipam/plugins/module_utils/phpipam_helper.py\", line 122, in find_entity\n  File \"/home/user/ansible/lib/python3.8/site-packages/phpypam/core/api.py\", line 167, in get_entity\n    return self._query(token=self._api_token, method=GET, path=_path, params=_params)\n  File \"/home/user/ansible/lib/python3.8/site-packages/phpypam/core/api.py\", line 124, in _query\n    raise PHPyPAMException(code=result['code'], message=result['message'])\n  File \"/home/user/ansible/lib/python3.8/site-packages/phpypam/core/exceptions.py\", line 44, in __init__\n    raise PHPyPAMInvalidSyntax(message=self._message)\nphpypam.core.exceptions.PHPyPAMInvalidSyntax: Invalid filter_by\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by cmeissner** [comment]
> Great news!
> 
> With play:
> 
> * name: Create a folder in DC
>   folder:
>   app_id: "{{ app_id }}"
>   username: "{{ username }}"
>   password: "{{ password }}"
>   server_url: "{{ server_url }}"
>   name: "BACKBONE"
>   section: "section_name"
>   state: present
> 
> i got error:

I can't reproduce the error. Neither with your play nor with the test from our repository. You can reproduce the work locally as followed (having a pyton env inplace is a good idea):

1. Make sure the following environment variables exists:

```shell
PYTHONWARNINGS="ignore:Unverified HTTPS request"
PHPIPAM_VERSION=1.4.1
PHPIPAM_PORT=8443
PHPIPAM_URL=https://locahost:8443
PHPIAPM_APP_ID=ansible
PHPIPAM_USERNAME=admin
PHPIPAM_PASSWORD=ipamadmin
PHPIPAM_VALIDATE_CERTS=false
```

2. Setup test enviromentment

```shell
$ make setup-phpipam
# ... some output ...
```

3. Run `folder` test

```shell
$ make test-folder
WARNING: You are using pip version 21.2.4; however, version 23.2.1 is available.
You should consider upgrading via the '/home/cmeissne/.pyenv/versions/3.9.8/envs/pam/bin/python3.9 -m pip install --upgrade pip' command.
coverage run -m pytest --forked -vv 'tests/test_crud.py::test_case_crud' --testcase folder 
============================= test session starts ==============================
platform linux -- Python 3.9.8, pytest-7.1.2, pluggy-1.0.0 -- /home/cmeissne/.pyenv/versions/3.9.8/envs/pam/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/cmeissne/Development/github/cmeissner/phpipam-ansible-modules
plugins: forked-1.4.0, xdist-2.5.0, typeguard-2.13.3
collected 1 item                                                               

tests/test_crud.py::test_case_crud PASSED                                [100%]

============================== 1 passed in 2.55s ===============================
```

If you need more output from the test case you can either run it via `ansible-playbook tests/test_playbooks/folder.yml` or `pytest -vvv -rP tests/test_crud.py::test_case_crud --testcase folder`.

You can also run your playbook against this test environment. 

From my point of view the module should work.

**Comment by ingvarrwvw** [comment]
Yes, it works, thanks
