### ISSUE TITLE
Subnet boolean values not working

### ISSUE THREAD

**Issue by Swaeltjie** [codeaffen/phpipam-ansible-modules#90]
**Describe the bug**
Certain boolean values of the subnet playbook is providing an error. 

**To Reproduce**
Change value of 'ping_subnet', 'discover_subnet' or 'is_folder' to 'true' or 'yes'.

`---
base_subnet_data:
  cidr: 10.0.0.0/24
  section: "Private IPv4"
  ping_subnet: yes
  discover_subnet: yes
  is_folder: yes
`

**Expected behavior**
Expect the playbook to recognize the value is set to yes and have the subnet be created successfully with the values shown on the GUI. 

**Versions:**

- Ansible: 2.13.5
- phpipam-ansible-modules: 1.6.0
- phpypam: 1.0.2

**Additional context**
Full error log attached
[ansible_error.txt](https://github.com/codeaffen/phpipam-ansible-modules/files/9926731/ansible_error.txt)

**Comment by cmeissner** [comment]
@Swaeltjie thank you for bringing this issue to our attention. It seems to be an issue with camelizing of module parameters. I will start working on this issue. Stay tuned
