### ISSUE TITLE
Problem with option show_supernets_only

### ISSUE THREAD

**Issue by ingvarrwvw** [codeaffen/phpipam-ansible-modules#98]
Hi!

When using option "show_supernet_only" i get exception:

phpypam.core.exceptions.PHPyPAMInvalidSyntax: Invalid request key showSupernetsOnly

**To Reproduce**
use option "show_supernet_only" in playbook

**Expected behavior**
Section created

**Versions:**

- Ansible: 2.13
- phpipam-ansible-modules: 1.6.1
- phpypam: 1.0.2

**Comment by cmeissner** [comment]
@ingvarrwvw thank you for bringing this to our attention. I can confirm the issue. I will work on the issue as soon as I found some time for fixing.
